---
title: "Visualizations"
output:
  html_document: default
  pdf_document: default
---

```{r load-data, echo = FALSE} 
library(readr)
library(tidyverse)
library(forcats)
library(kableExtra)
library(sf)
library(leaflet)
library(ggridges)
#install.packages("naniar")
library(naniar)
# install.packages("devtools")
#devtools::install_github("nhs-r-community/nhsrtheme")

district_demographics <- read_csv("https://raw.githubusercontent.com/invinst/chicago-police-data/master/data/context_data/district_demographics/Districts.csv")

active_duty_officers <- read_csv("https://raw.githubusercontent.com/invinst/chicago-police-data/master/data/context_data/CPD%20Employees%20active-duty-only.csv")

#The officers accused
complaints_accused <- read_csv("data/complaints-accused_2000-2016_2016-11.csv")

#those who made the complaints
complainants <- read_csv("data/complaints-complainants_2000-2016_2016-11 (1).csv")

#What complaints were made (more categorical data)
complaints_made <- read_csv("data/complaints-complaints_2000-2016_2016-11 (1).csv")

units <- read.csv("https://raw.githubusercontent.com/invinst/chicago-police-data/master/data/context_data/current_and_past_units/Current_and_Past_CPD_Units_2016-05-06.csv")
```


```{r data-joins, fig.alt = "Scatterplot of police complaints per capita by district name colored by racial majority. Visualization shows "}
district_complaints <- complaints_accused %>%
  filter(current_unit %in% 1:25) %>%
  group_by(current_unit) %>%
  summarise(n = n()) %>%
  arrange(desc(n))

total_district_complaints <- full_join(district_complaints,
                                       district_demographics,
                                       by = c("current_unit" = "District_No")) %>%
  mutate(complaints_per_capita = n/Population)

total_district_complaints %>%
  filter(is.na(District_Name) == FALSE) %>%
         ggplot(mapping = aes(
                  x = fct_reorder(District_Name, complaints_per_capita),
                  y = complaints_per_capita, 
                color = Majority)) +
  geom_point() +
  geom_segment(aes(x = fct_reorder(District_Name, complaints_per_capita), 
                   xend = fct_reorder(District_Name, complaints_per_capita), 
                   y = 0, yend = complaints_per_capita)) +
  coord_flip() +
  labs(title = "Complaints per Capita by District Name",
       subtitle = "Colored by Racial Majority",
       x = "District Name",
       y = "Complaints Per Capita")
```
  
```{r proportion-findings-vis}
district_complaints_1 <- complaints_accused %>%
  filter(current_unit %in% 1:25) %>%
  group_by(current_unit)

total_district_complaints_findings <- full_join(district_complaints_1,
                                       district_demographics,
                                       by = c("current_unit" = "District_No"))

#stat = "identity"

data1 <- total_district_complaints_findings %>%
  mutate(final_decision = 
           as.factor(case_when(final_finding %in% "SU" ~ "Sustained",
                               final_finding %in% "DIS" ~ "Sustained",
                               is.na(final_finding) == TRUE ~ "Missing",
                               final_finding %in% "NAF" ~ "No Affidavit or Cooperation",
                               final_finding %in% "NC" ~ "No Affidavit or Cooperation",
                               final_finding %in% "NS" ~ "Not Sustained",
                               final_finding %in% "EX" ~ "Not Sustained",
                               final_finding %in% "UN" ~ "Not Sustained",
                               ))) %>%
  group_by(final_decision, District_Name)  %>%
  summarize(n = n())

data1 %>%
  group_by(final_decision) %>%
  summarize(n = n())

#reorder so that missing is at the end and change colors, take out the NA
  data1 %>%   
  filter(is.na(District_Name) == FALSE) %>%
  ggplot(aes(fill = factor(final_decision, 
                           levels = c("Missing", 
                                      "Not Sustained", 
                                      "No Affidavit or Cooperation", 
                                      "Sustained")),
             x = fct_rev(fct_relevel(District_Name, 
                                     "Central",
                                     "Englewood",
                                     "Harrison",
                                     "Calumet",
                                     "Grand Crossing",
                                     "Gresham",
                                     "Austin",
                                     "Morgan Park",
                                     "Wentworth",
                                     "Near North",
                                     "South Chicago",
                                     "Ogden",
                                     "Lincoln",
                                     "Near West",
                                     "Chicago Lawn",
                                     "Deering",
                                     "Shakespeare",
                                     "Town Hall",
                                     "Rogers Park",
                                     "Grand Central",
                                     "Albany Park",
                                     "Jefferson Park")), 
                                     district_levels,
             y = n)) +
  geom_bar(position = "fill", stat = "identity") +
  theme_minimal() +
  scale_fill_viridis_d() +
  coord_flip() +
   labs(title = "Proportion of Final Findings",
        subtitle = "By District",
        x = "District Name",
        y = "Proportion of Complaints",
        fill = "Final Decision"
        ) 

```
```{r some summary stats}
total_district_complaints_findings %>%
  group_by(final_finding) %>%
  summarise(n = n(), perc_of_data = (n/71960)*100)
```
  
```{r complaints for sustained decisions}
sustained_data <- total_district_complaints_findings %>%
  group_by(final_finding, District_Name, Majority, Population) %>%
  filter(final_finding == "SU") %>%
  filter(is.na(District_Name) == FALSE) %>%

  summarize(n = n()) %>%
  mutate(complaints_per_capita = n/Population) 
  

  ggplot(data = sustained_data, 
                mapping = aes(
                x = fct_rev(fct_relevel(District_Name, 
                                     "Central",
                                     "Englewood",
                                     "Harrison",
                                     "Calumet",
                                     "Grand Crossing",
                                     "Gresham",
                                     "Austin",
                                     "Morgan Park",
                                     "Wentworth",
                                     "Near North",
                                     "South Chicago",
                                     "Ogden",
                                     "Lincoln",
                                     "Near West",
                                     "Chicago Lawn",
                                     "Deering",
                                     "Shakespeare",
                                     "Town Hall",
                                     "Rogers Park",
                                     "Grand Central",
                                     "Albany Park",
                                     "Jefferson Park")),
                  y = complaints_per_capita, 
                color = Majority)) +
  geom_point() +
    geom_segment(aes(x = fct_reorder(District_Name, complaints_per_capita), 
                     xend = fct_reorder(District_Name, complaints_per_capita), 
                   y = 0,
                   yend = complaints_per_capita)) +
  coord_flip() +
  labs(title = " Sustained Complaints per Capita by District Name",
       subtitle = "Colored by Racial Majority",
       x = "District Name",
       y = " Sustained Complaints Per Capita")
```
  
```{r complaints for no cooperation/affidavit decisions}

no_ca_data <- total_district_complaints_findings %>%
  group_by(final_finding, District_Name, Majority, Population) %>%
  filter(final_finding == "NAF") %>%
  filter(is.na(District_Name) == FALSE) %>%
  summarize(n = n()) %>%
  mutate(complaints_per_capita = n/Population) 
  

  ggplot(data = no_ca_data, 
                mapping = aes(
                  x = fct_rev(fct_relevel(District_Name, 
                                     "Central",
                                     "Englewood",
                                     "Harrison",
                                     "Calumet",
                                     "Grand Crossing",
                                     "Gresham",
                                     "Austin",
                                     "Morgan Park",
                                     "Wentworth",
                                     "Near North",
                                     "South Chicago",
                                     "Ogden",
                                     "Lincoln",
                                     "Near West",
                                     "Chicago Lawn",
                                     "Deering",
                                     "Shakespeare",
                                     "Town Hall",
                                     "Rogers Park",
                                     "Grand Central",
                                     "Albany Park",
                                     "Jefferson Park")),
                  y = complaints_per_capita, 
                color = Majority)) +
  geom_point() +
    geom_segment(aes(x = fct_reorder(District_Name, complaints_per_capita), 
                     xend = fct_reorder(District_Name, complaints_per_capita), 
                   y = 0,
                   yend = complaints_per_capita)) +
  coord_flip() +
  labs(title = "Complaints Missing Affidavit per Capita by District",
       subtitle = "Colored by Racial Majority",
       x = "District",
       y = "Complaints Missing Affidavit per Capita")
```
  
```{r stats about demographics}

#The districts of which demogrpahic majoirty compromise most of the data?

total_district_complaints_findings %>%
  group_by(Majority) %>%
  summarise(n = n(), prop_of_data = n/71960)
```
  
```{r complaints for missing data}
missing_data <- total_district_complaints_findings %>%
  group_by(final_finding, District_Name, Majority, Population) %>%
  filter(is.na(final_finding)) %>%
  filter(!is.na(District_Name)) %>%
  summarize(n = n()) %>%
  mutate(complaints_per_capita = n/Population) 
  
 ggplot(data = missing_data, 
                mapping = aes(
                  x = fct_rev(fct_relevel(District_Name, 
                                     "Central",
                                     "Englewood",
                                     "Harrison",
                                     "Calumet",
                                     "Grand Crossing",
                                     "Gresham",
                                     "Austin",
                                     "Morgan Park",
                                     "Wentworth",
                                     "Near North",
                                     "South Chicago",
                                     "Ogden",
                                     "Lincoln",
                                     "Near West",
                                     "Chicago Lawn",
                                     "Deering",
                                     "Shakespeare",
                                     "Town Hall",
                                     "Rogers Park",
                                     "Grand Central",
                                     "Albany Park",
                                     "Jefferson Park")),
                  y = complaints_per_capita, 
                color = Majority)) +
  geom_point() +
   geom_segment(aes(x = fct_reorder(District_Name, complaints_per_capita), 
                    xend = fct_reorder(District_Name, complaints_per_capita), 
                   y = 0, 
                   yend = complaints_per_capita)) +
  coord_flip() +
  labs(title = " Missing Complaints per Capita by District Name",
       subtitle = "Colored by Racial Majority",
       x = "District Name",
       y = " Missing Complaints Per Capita")
```
  
```{r chicago spatial data}
#no 21 or 23 district but 31st district included?

chicago_police_district_spatial <- st_read(dsn = "/cloud/project/data/geo_export_2efb16ec-aa66-49b0-92a0-2d6f5e0f81d9.shp")


total_district_complaints_spatial <- total_district_complaints %>%
  mutate(`Latino%` = str_remove(`Latino%`, "%"),
         `White%` = str_remove(`White%`, "%"),
         `Black%` = str_remove(`Black%`, "%"),
         `Asian%` = str_remove(`Asian%`, "%"),
         `Native_American%` = str_remove(`Native_American%`, "%"),
         `Other%` = str_remove(`Other%`, "%"),
         `Latino%` = as.numeric(`Latino%`),
         `White%` = as.numeric(`White%`),
         `Black%` = as.numeric(`Black%`),
         `Asian%` = as.numeric(`Asian%`),
         `Native_American%` = as.numeric(`Native_American%`),
         `Other%` = as.numeric(`Other%`)) %>%
  mutate(current_unit = as.character(current_unit))%>%
  left_join(chicago_police_district_spatial,
                                    by = c("current_unit" = "dist_num")) %>%
  st_as_sf() %>%
  st_transform("+init=epsg:4326")

write.csv(total_district_complaints_spatial, file = "data/total_district_complaints_spatial.csv")

bins <- seq(from = 0, to = 100, by = 12.5)
pal_perc <- colorBin("OrRd", domain = total_district_complaints_spatial , bins = bins)
#https://laurielbaker.github.io/DSCA_leaflet_mapping_in_r/slides/leaflet_slides3.html#58
 
m <- leaflet(total_district_complaints_spatial) %>%
# Now add tiles to it
  addTiles() %>%
# Setting the middle of where the map should be and the zoom level
  setView(-87.633506, 41.876067, zoom = 9.5) %>%
  addProviderTiles(providers$CartoDB.Positron)
```
  
```{r Black-perc-leaflet}
Black_perc_m <- m %>%
  addPolygons(
    fillOpacity = 1,
    color = "black",
    opacity = 0.7,
    weight = 1,
    fillColor = ~pal_perc(total_district_complaints_spatial$`Black%`),
    highlightOptions = highlightOptions(
    weight = 5,
    color = "#666",
    fillOpacity = 0.7,
    bringToFront = FALSE))

Black_perc_m <- Black_perc_m %>%
  addLegend(
    position = "topright",
    pal = pal_perc,
    values = ~total_district_complaints_spatial$`Black%`,
    title = "Percent Black residents",
    opacity = 1)

Black_perc_m
```
  
```{r White-perc-leaflet}
 White_perc_m <- m %>%
   addPolygons(
     fillOpacity = 1,
     color = "black",
     opacity = 0.7,
     weight = 1,
     fillColor = ~pal_perc(total_district_complaints_spatial$`White%`))
       
 White_perc_m <- White_perc_m %>%
   addLegend(
     position = "topright",
     pal = pal_perc,
     values = ~total_district_complaints_spatial$`White%`,
     title = "Percent White residents",
     opacity = 1)
 
 White_perc_m
```

```{r Latino-perc-leaflet}
# Latino_perc_m <- m %>%
#   addPolygons(
#     fillOpacity = 1,
#     color = "black",
#     opacity = 0.7,
#     weight = 1,
#     fillColor = ~pal_perc(total_district_complaints_spatial$`Latino%`))
#       
# Latino_perc_m <- Latino_perc_m %>%
#   addLegend(
#     position = "topright",
#     pal = pal_perc,
#     values = ~total_district_complaints_spatial$`Latino%`,
#     title = "Percent Latino residents",
#     opacity = 1)
# 
# Latino_perc_m
```

```{r complaints-perc-leaflet}
# creating map showing neighborhoods with most missing data ie when the final finding is either NA (missing), NAF (no affidavit) or NC (no affidavit)
#baseline complaints per capita
 
# bins_2 <- seq(from = 0, to = 0.06, by = 0.01)
# pal_per_cap <- colorBin("OrRd", domain = total_district_complaints_spatial, bins = bins_2)
# 
#  complaints_perc_m <- m %>%
#   addPolygons(
#     fillOpacity = 1,
#     color = "black",
#     opacity = 0.7,
#     weight = 1,
#     fillColor = ~pal_per_cap(total_district_complaints_spatial$`complaints_per_capita`))
#       
# complaints_perc_m <- complaints_perc_m %>%
#   addLegend(
#     position = "topright",
#     pal = pal_per_cap,
#     values = ~total_district_complaints_spatial$`complaints_per_capita`,
#     title = "Complaints per capita",
#     opacity = 1)
# 
# complaints_perc_m

```
